Repository TreinaDev/checkout_area_do_cliente, pull requests merged in 2020-07, with the labels that each got.

#44 Layout: formulário de login do vendedor
  app/assets/images/access_account.svg
  app/assets/images/avatar.svg
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/form_login_register.scss
  app/assets/stylesheets/home_page.scss
  app/views/clients/sessions/new.html.erb
  app/views/employees/sessions/new.html.erb
  app/views/employees/shared/_links.html.erb
  app/views/shared/_flashes.html.erb
  config/locales/employee.pt-BR.yml
Labels: enhancement

#47 Layout: formulário para criar/editar empresas
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/form_edit_new.scss
  app/assets/stylesheets/form_login_register.scss
  app/assets/stylesheets/home_page.scss
  app/views/companies/_form.html.erb
  app/views/companies/_headers_errors.html.erb
  app/views/companies/edit.html.erb
  app/views/companies/new.html.erb
Labels: enhancement

#46 Layout: Página de informações da empresa do cliente
  app/assets/images/personal_info.svg
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/company_show.scss
  app/assets/stylesheets/form_login_register.scss
  app/assets/stylesheets/home_page.scss
  app/views/companies/show.html.erb
Labels: enhancement

#48 Layout menu
  app/assets/images/bot-icon.png
  app/assets/stylesheets/form_login_register.scss
  app/assets/stylesheets/home_page.scss
  app/views/layouts/application.html.erb
Labels: enhancement

#49 Layout: Cards com os planos e home page
  app/assets/images/empty.svg
  app/assets/images/undraw_file_analysis.png
  app/assets/images/undraw_online_messaging.png
  app/assets/stylesheets/home_page.scss
  app/assets/stylesheets/home_page_plans.scss
  app/controllers/plans_controller.rb
  app/views/home/_plans.html.erb
  app/views/home/index.html.erb
  app/views/plans/_plans.html.erb
Labels: enhancement

#34 Vendedor Aprova Pedidos
  app/controllers/application_controller.rb
  app/controllers/approved_orders_controller.rb
  app/controllers/order_clients_controller.rb
  app/models/approved_order.rb
  app/models/order_client.rb
  app/views/layouts/application.html.erb
  app/views/order_clients/index.html.erb
  app/views/order_clients/show.html.erb
  config/locales/company.pt-BR.yml
  config/locales/models.yml
  config/locales/order_client.pt-BR.yml
  config/routes.rb
  db/migrate/20200629202311_create_order_clients.rb
  db/migrate/20200630185204_add_status_to_order_clients.rb
  db/migrate/20200630202603_create_approved_orders.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/approved_orders.rb
  spec/factories/order_clients.rb
  spec/features/client/logs_in_spec.rb
  spec/features/client/purchases_plan_spec.rb
  spec/features/client/registers_spec.rb
  spec/features/employee/approve_order_spec.rb
  spec/features/visitor_see_plans_spec.rb
Labels: enhancement

#51 Corrigindo quebras no layout
  app/assets/stylesheets/company_show.scss
  app/assets/stylesheets/home_page.scss
  app/assets/stylesheets/home_page_plans.scss
  app/views/clients/registrations/new.html.erb
Labels: bug

#50 Cliente pode ver histórico de compras
  app/controllers/companies_controller.rb
  app/models/client.rb
  app/views/companies/orders.html.erb
  app/views/companies/show.html.erb
  app/views/home/_plans.html.erb
  app/views/order_clients/show.html.erb
  config/locales/company.pt-BR.yml
  config/locales/employee.pt-BR.yml
  config/routes.rb
  spec/features/client/client_view_historic_purchases_spec.rb
Labels: enhancement

#58 Layout: Tabela de pedidos
  app/assets/stylesheets/order_clients.scss
  app/views/client/order_clients/index.html.erb
  app/views/layouts/application.html.erb
  app/views/order_clients/index.html.erb
  app/views/order_clients/show.html.erb
  app/views/shared/_orders.html.erb
  spec/features/employee/approve_order_spec.rb
Labels: bug

#72 Readme
  README.md
  db/seeds.rb
Labels: documentation

#76 Layout: lista com promoções
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/promo.scss
  app/views/promos/_promo.html.erb
  app/views/promos/index.html.erb
  db/seeds.rb
  spec/features/employee/approve_promo_spec.rb
Labels: Layout

#71 Enviar api compra
  Gemfile
  Gemfile.lock
  app/controllers/approved_orders_controller.rb
  app/views/layouts/application.html.erb
  app/views/order_clients/show.html.erb
  config/locales/approve_orders.pt-BR.yml
  db/migrate/20200710184510_add_bot_token_to_approved_order.rb
  db/schema.rb
  spec/factories/approved_orders.rb
  spec/features/employee/approve_order_spec.rb
  spec/features/employee/order_to_api_spec.rb
Labels: enhancement
